# Generated by Django 3.0.5 on 2020-04-04 20:30

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('title', models.CharField(max_length=300, verbose_name='Post Title')),
                ('category', models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food'), ('Adventure', 'Adventure'), ('Business', 'Business')], max_length=250)),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date Publish')),
                ('detail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('up_detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publish post')),
            ],
        ),
    ]
